var listCitacoes = [
    "Na manufatura e no artesanato, o trabalhador utiliza a ferramenta; na fábrica, ele é um servo da máquina.\n\n-Karl Marx",
    "QUESTÃO DE CRIATIVIDADE : Na Arte e no Artesanato não é o material, mas o resultado que deve ser NOBRE...\n\n-CANAL ARTE 1 ( 115 na NET )",
    "O verdadeiro artista é aquele que sabe enxergar o lado bom das coisas e reciclar o que não serve para transformar tudo em uma obra prima.\n\n-anderson",
    "A excelência ecológica é não ter o que reciclar!\n\n-Somel Serip Pensador",
    "Reciclar-se sempre, para se imaginar no futuro.\n\n-Jefferson Alves da Silva",
    "A sustentabilidade se resume em três palavras: Reduzir, Reusar, Reciclar.\n\n-Herbert Alexandre Galdino Pereira",
    "Se você não aprender a reciclar, a vida vai acabar reciclando você.\n\n-Cello Vieira",
    "Somos responsáveis em fazer lixo, mais não em reciclar, essa é nossa sociedade individualista no qual estamos caminhando.\n\n-Samuel Jadson",
    "Reciclamos para dar nova vida aos materiais e ao Universo.\n\n-Rita Padoin",
    "Quando reciclamos, estamos transformando o bem material usado, em novo.\n\n-Rita Padoin",
    "Eu procuro por mim, tal qual o artesão procura sua arte escondida nos excessos da matéria bruta de seu mármore.\n\n-Padre Fábio de Melo",
    "Primeiro aprenda a ser um artesão. Isso não impedirá você de ser um gênio.\n\n-Eugène Delacroix",
    "A ostra é possessiva pela pérola. Mas é o artesão que faz ela se sentir uma jóia.\n\n-Mark Mendonça",
    "A sutileza de um artesão não pode ser comparada com a \"perfeição\" das máquinas...\n\n-Mark Mendonça",
    "A vida é como um novelo de lã que ao desenrolar se torna arte nas mãos de um artesão.\n\n-Djoser",
    "É preciso ser um reciclador do passado, para ser um artesão do presente.\n\n-Gustavo Lacerda",
    "Há dois homens no interior do artista: o poeta e artesão. Um já nasce poeta; o outro se torna artesão.\n\n-Émile Zola",
];